version: 2

jobs:
  build:
    docker:
      - image: bitwalker/alpine-elixir-phoenix:1.6.6
    steps:
      - add_ssh_keys
      - checkout
      - run: apk update
      - run: apk add --no-cache yarn rsync openssh
      - run: ls ~/.ssh
      - run: ssh-keyscan $HOST >> ~/.ssh/known_hosts
      - run: ls ~/.ssh
      - run: cat ~/.ssh/config
      # - run:
      #     command: mix do deps.get, compile
      #     working_directory: api
      - run:
          command: yarn && yarn build
          working_directory: client
      - run: rsync -va --delete client/build/* $CI_USER@$HOST:$CLIENT_DIR
