version: 2

jobs:
  build:
    docker:
      - image: bitwalker/alpine-elixir-phoenix:1.6.6
    steps:
      - add_ssh_keys
      - checkout
      - run: apk update
      - run: apk add --no-cache yarn rsync
      - run: ssh-keyscan $HOST github.com >> ~/.ssh/known_hosts
      # - run:
      #     command: mix do deps.get, compile
      #     working_directory: api
      - run:
          command: yarn && yarn build
          working_directory: client
      # FIXME: I don't know why setting UserKnownHostsFile is necessary
      - run: rsync -e "ssh -o UserKnownHostsFile=~/.ssh/known_hosts" -va --delete client/build/* $CI_USER@$HOST:$CLIENT_DIR
